config/routes.rb
EquipmentTracker::Application.routes.draw do

  resources :equipment do
    collection do
      post :import
    end
    resources :loans
    resources :services do
      resources :serviceparts
      resources :serviceimages
    end
    member do
      match 'startoggle' => 'equipment#startoggle'
      match 'invreset' => 'equipment#invreset'
    end
  end
  
  resources :services do
    member do
      match 'serviceRequest' => 'services#serviceRequest'
    end
    resources :serviceparts
    resources :serviceimages
  end
  
  resources :serviceparts do
    resources :parts
  end
  
  resources :serviceimages
  
  resources :parts do
    member do
      match 'invreset' => 'parts#invreset'
    end
  end

  resources :loans
  
  devise_for :users
  
  resources :users do
    member do
      match 'invmodetoggle' => 'users#invmodetoggle'
    end
  end

  get 'about' => 'pages#about'
  
  get 'part' => 'part#index'
  
  get 'archived' => 'equipment#archived'
  
  get 'service' => 'services#index'

  get 'holdlist' => 'equipment#holdlist'    

  get 'openloan' => 'loans#index' 

  get 'equipment' => 'equipment#index'
  
  root :to => 'equipment#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :mileage, :notes, :operatinghours, :servicedate, :serviceduration, :serviceperformed, :servicecost, :laborcost, :materialcost, :completed

  has_many :serviceparts, dependent: :destroy
  has_many :serviceimages, dependent: :destroy
  belongs_to :equipment
  has_paper_trail
  
  def self.search(search)
    if search
      find(:all, :order => 'servicedate desc', :conditions => ['lower(serviceperformed) LIKE lower(?) OR lower(notes) LIKE lower(?)', "%#{search}%", "%#{search}%"])
    else
      find(:all, :order => 'servicedate desc')
    end
  end
  
  def servicepartcostTotal
    serviceparts.map do |i|
      if !i.part_id.blank?
        then Part.find(i.part_id).cost*i.qty
      else servicepartcostTotal=0.00
      end
    end.sum
  end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user! #, except: [:index]
  # GET /services
  # GET /services.json
  helper_method :sort_column, :sort_direction
  
  def index
    @services = Service.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])
    @parts = Part.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    if params[:commit] == "Add Service Record"
      @equipment = Equipment.find(params[:equipment_id])
      @service = @equipment.services.create(params[:service])
      @service.materialcost = (if !@service.materialcost.blank? then @service.materialcost else 0.00 end)
      @service.laborcost = (if !@service.laborcost.blank? then @service.laborcost else 0.00 end)
      @service.servicecost = (if !@service.laborcost.blank? then @service.laborcost else 0.00 end) + (if !@service.materialcost.blank? then @service.materialcost else 0.00 end)
      @service.save
      redirect_to equipment_path(@equipment, :scan => 0), notice: 'Service entry has been recorded.'
    else
      @equipment = Equipment.find(params[:equipment_id])
      @service = @equipment.services.create(params[:service])
      holdnotes = "Service requested by " + current_user.name + " on " + Date.today.to_s + ": " + @service.serviceperformed
      @techemail = ENV["TECH_EMAIL"]
      @user = current_user
      @equipment.hold=true
      @equipment.holdnotes=holdnotes
      @service.materialcost = (if !@service.materialcost.blank? then @service.materialcost else 0.00 end)
      @service.laborcost = (if !@service.laborcost.blank? then @service.laborcost else 0.00 end)
      @service.servicecost = (if !@service.laborcost.blank? then @service.laborcost else 0.00 end) + (if !@service.materialcost.blank? then @service.materialcost else 0.00 end)
      @service.save
      @equipment.save
      if user_signed_in?
        UserMailer.request_service(@equipment, @techemail, @user, @service).deliver
        redirect_to equipment_path(@equipment, :scan => 0), notice: 'Service request has been sent.'
      else
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        @service.servicecost = (if !@service.laborcost.blank? then @service.laborcost else 0.00 end) + (if !@service.materialcost.blank? then @service.materialcost else 0.00 end)
        @service.save
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to equipment_path(@service.equipment_id, :scan => 0)
  end
  
  def serviceRequest
    @techemail = "darrell@hls2.com"
    @user = current_user
    @equipment = Equipment.find(params[:id])
    @equipment.hold=true
    @equipment.save
    if user_signed_in?
      UserMailer.request_service(@equipment, @techemail, @user).deliver
      redirect_to equipment_path(@equipment, :scan => 0), notice: 'Service request has been sent.'
    else
    end
  end
  
  private
  
  def sort_column
    Service.column_names.include?(params[:sort]) ? params[:sort] : "servicedate"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
  
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for(@service, html: { class: "form-horizontal"}) do |f| %>

  <div class="form-inputs">
    <%= f.input :serviceperformed, label: "Service Req." %>
    <%= f.input :servicedate, label: "Service Date", :input_html => {:style => 'width: 105px'} %>
    <% if @service.equipment.equipmenttype == "Vehicle" %>
    	<%= f.input :mileage %>
    <% else %>
    	<%= f.input :operatinghours, label: "Operating Hours" %>
    <% end %>
    <%= f.input :serviceduration, label: "Service Duration" %>
    <%= f.input :laborcost, label: "Labor Cost ($)" %>
    <%= f.input :materialcost, label: "Material Cost ($)" %>
    <%= f.input :notes, :input_html => {:style => 'width: 365px; height: 100px'} %><br />
    <%= f.input :completed, label: "Service Completed" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/services/_service.html.erb
<tr onclick="window.location.href = '<%= service_path(service) %>'" style="cursor: pointer">
  <td title="<%= if service.completed? then "" else "Incomplete" end %>" width="10px"><span class="<%= if service.completed? then "" else "icon-flag" end %>"></span></td>
  <td title="<%= if service.notes? then service.notes else "No notes" end %>"><%= service.serviceperformed %></td>
  <td title="<%= if service.equipment.description? then service.equipment.description else "No notes" end %>"><%= link_to service.equipment.unitname, equipment_path(service.equipment_id, :scan => 0) %><%= if !service.equipment.crew.empty? then ("-" + service.equipment.crew) else "" end %></td>
  <td><%= service.servicedate %></td>
  <% if service.equipment.equipmenttype == "Vehicle" %>
   	<td><%= service.mileage %></td>
  <% else %>
  	<td><%= service.operatinghours %></td>
  <% end %>
  <td style="text-align: right"><%= number_to_currency(service.servicecost, :unit => "$") %></td>
  <td><%= link_to (content_tag :i, "", class: "icon-list-alt"), service_path(service), :class => "btn" %></td>
  <td><%= link_to (content_tag :i, "", class: "icon-edit"), edit_service_path(service), :class => "btn" %></td>
</tr>

app/views/services/_serviceimageForm.html.erb
<h4>Add an image to this service:</h4>
<%= simple_form_for([@service, @service.serviceimages.build], html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>
	<div class="form-inputs">
		<%= f.input :image, label: "Upload an image" %>
	    <%= f.input :caption, label: "Caption", :input_html => {:autofocus => ''} %>
	</div>    
	<div class="form-actions">
	  <%= f.button :submit, :value => "Add Image", class: "btn btn-primary" %>
	  <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
	</div>
<% end %>

app/views/services/_servicepartForm.html.erb
<h4>Add a part to this service:</h4>

<div class="form-inputs">
	<%= simple_form_for([@service, @service.serviceparts.build], html: { class: "form-horizontal"}) do |f| %>
		<%= f.input :part_id, collection: @parts, label_method: :name, value_method: :id, prompt: "Select a part" %>
	    <%= f.input :qty, label: "Qty", :input_html => {:autofocus => ''} %>
	    
	  <div class="form-actions">
	    <%= f.button :submit, :value => "Add Part", class: "btn btn-primary" %>
	    <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
	  </div>
	<% end %>
</div>

app/views/services/edit.html.erb
<div class="well">
	<h4>Editing service record for <%= @service.equipment.unitname %></h4>
	<br />
	<%= render 'form' %>
	
	<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>
</div>

app/views/services/index.html.erb
<% if user_signed_in? %>
	<div>
		<%= form_tag services_path,  :method => 'get' do %>
		  <p>
		    <%= text_field_tag :search, params[:search] %>
		    <%= submit_tag "Lookup", :serviceperformed => nil, class: "btn btn-primary" %>
		  </p>
		<% end %>
	</div>

	<h2>Service Listing</h2>
	
	<table class="table table-striped">
		<thead>
			<tr>
				<th title="Incomplete"><%= sortable "completed", "<span class='icon-flag'></span>", params[:search], params[:typefilter] %></th>
			    <th><%= sortable "serviceperformed", "Service", params[:search], params[:typefilter] %></th>
			    <th>Unit Name</th>
			    <th><%= sortable "servicedate", "Service Date", params[:search], params[:typefilter] %></th>
			    <th>Mileage/Op. Hours</th>
			    <th style="text-align: center">Cost</th>
			    <th></th>
			    <th></th>
			    <th></th>
			</tr>
		</thead>
		<tbody>
			<%= render @services %>
		</tbody>
	</table>
	<%= will_paginate @services %>
	<br />
<% end %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>

app/views/services/show.html.erb
<div class="row">
	<div class="span9 offset1">
		<div class="well">
			<h4>Service Detail for <%= link_to @service.equipment.unitname, equipment_path(@service.equipment_id, :scan => 0) %><%= if !@service.equipment.crew.empty? then ("-" + @service.equipment.crew) else "" end %><div class="pull-right incomplete"><%= if @service.completed? then "" else "NOT COMPLETED" end %></div></h4>
			<br />
			<p>
			  <b>Service Req.:</b>
			  <%= @service.serviceperformed %>
			</p>
			
			<p>
			  <b>Service Date:</b>
			  <%= @service.servicedate %>
			</p>
			
			<% if @service.equipment.equipmenttype == "Vehicle" %>
				<p>
				  <b>Mileage:</b>
				  <%= @service.mileage %>
				</p>
			<% else %>
				<p>
				  <b>Operating Hours:</b>
				  <%= @service.operatinghours %>
				</p>
			<% end %>
			
			<p>
			  <b>Service Duration:</b>
			  <%= @serviceserviceduration %>
			</p>
			
			<p>
			  <b>Labor Cost:</b>
			  <%= number_to_currency(@service.laborcost, :unit => "$") %>
			</p>
			
			<p>
			  <b>Material Cost:</b>
			  <%= number_to_currency(@service.materialcost, :unit => "$") %>
			</p>
			
			<p>
			  <b>Service Cost:</b>
			  <%= number_to_currency(@service.servicecost, :unit => "$") %>
			</p>
			
			<p>
			  <b>Notes:</b>
			  <%= @service.notes %>
			</p>
			<br />
			
			<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>
			<%= link_to (content_tag :i, "", class: "icon-edit"), edit_service_path(@service), :class => "btn" %>
			<%= link_to (content_tag :i, "", class: "icon-trash"), @service, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn pull-right" %>
		</div>
		<div class="well">
			<h4>Parts Used <!-- Button trigger modal --><button class="btn btn-primary pull-right" data-toggle="modal" data-target="#addPartModal">Add Part</button></h4>
			<% if !@service.serviceparts.blank? %>
				<table class="table table-striped">
					<thead>
						<tr>
						    <th>Part Used</th>
						    <th style="text-align: right">Cost</th>
						    <th style="text-align: center">Qty</th>
						    <th></th>
						    <th></th>
						</tr>
					</thead>
					<tbody>
						<%= render @service.serviceparts %>
					</tbody>
				</table>
			<% else %>
			<p>There are no parts associated with this service.</p>
			<% end %>
			<!-- Service Modal -->
			<div class="modal hide fade in" id="addPartModal" tabindex="-1" role="dialog" aria-labelledby="addPartModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			        <h4 class="modal-title" id="addPartModalLabel"><%= @service.equipment.unitname %><%= if !@service.equipment.crew.empty? then ("-" + @service.equipment.crew) else "" end %> - <%= @service.serviceperformed %></h4>
			      </div>
			      <div class="modal-body">
					<%= render 'servicepartForm' %>
			      </div>
			    </div><!-- /.modal-content -->
			  </div><!-- /.modal-dialog -->
			</div><!-- /.modal -->
		</div>

		<div class="well" %>
			<h4>Attached Images <!-- Button trigger modal --><button class="btn btn-primary pull-right" data-toggle="modal" data-target="#addImageModal">Add Image</button></h4>
			<% if !@service.serviceimages.blank? %>
				<div id="serviceimages">
				  <%= render @service.serviceimages %>
				</div>
			<% else %>
			<p>There are no images attached to this service.</p>
			<% end %>
			<!-- Image Modal -->
			<div class="modal hide fade in" id="addImageModal" tabindex="-1" role="dialog" aria-labelledby="addImageModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			        <h4 class="modal-title" id="addImageModalLabel"><%= @service.equipment.unitname %><%= if !@service.equipment.crew.empty? then ("-" + @service.equipment.crew) else "" end %> - <%= @service.serviceperformed %></h4>
			      </div>
			      <div class="modal-body">
					<%= render 'serviceimageForm' %>
			      </div>
			    </div><!-- /.modal-content -->
			  </div><!-- /.modal-dialog -->
			</div><!-- /.modal -->
		</div>
	</div>
</div>

app/views/services/showDetail.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Barcode:</b>
  <%= @service.barcode %>
</p>

<p>
  <b>Serviceperformed:</b>
  <%= @service.serviceperformed %>
</p>

<p>
  <b>servicedate:</b>
  <%= @service.servicedate %>
</p>

<p>
  <b>Operatinghours:</b>
  <%= @service.operatinghours %>
</p>

<p>
  <b>Mileage:</b>
  <%= @service.mileage %>
</p>

<p>
  <b>Serviceduration:</b>
  <%= @serviceserviceduration %>
</p>

<p>
  <b>Notes:</b>
  <%= @service.notes %>
</p>

<p>
  <b>Part:</b>
  <%= @service.part %>
</p>

<p>
  <b>Equipment:</b>
  <%= @service.equipment %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>