config/routes.rb
EquipmentTracker::Application.routes.draw do

  resources :equipment do
    collection do
      post :import
    end
    resources :loans
    resources :services do
      resources :serviceparts
      resources :serviceimages
    end
    member do
      match 'startoggle' => 'equipment#startoggle'
      match 'invreset' => 'equipment#invreset'
    end
  end
  
  resources :services do
    member do
      match 'serviceRequest' => 'services#serviceRequest'
    end
    resources :serviceparts
    resources :serviceimages
  end
  
  resources :serviceparts do
    resources :parts
  end
  
  resources :serviceimages
  
  resources :parts do
    member do
      match 'invreset' => 'parts#invreset'
    end
  end

  resources :loans
  
  devise_for :users
  
  resources :users do
    member do
      match 'invmodetoggle' => 'users#invmodetoggle'
    end
  end

  get 'about' => 'pages#about'
  
  get 'part' => 'part#index'
  
  get 'archived' => 'equipment#archived'
  
  get 'service' => 'services#index'

  get 'holdlist' => 'equipment#holdlist'    

  get 'openloan' => 'loans#index' 

  get 'equipment' => 'equipment#index'
  
  root :to => 'equipment#index'

end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessible :category, :description, :location, :name, :partnumber, :cost, :onhand
  
  validates_presence_of :cost, :name, :partnumber, :onhand
  
  has_many :serviceparts
  has_paper_trail
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(name) LIKE lower(?) OR lower(partnumber) LIKE lower(?) OR lower(description) LIKE lower(?)', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_filter :authenticate_user! #, except: [:index]
  # GET /parts
  # GET /parts.json
  helper_method :sort_column, :sort_direction, :filter_category
  
  def index
    if filter_category.blank?
      @parts = Part.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).search(params[:search])
    else
      @parts = Part.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).where(category: filter_category).search(params[:search])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.csv {if filter_category.blank?
        @parts = Part.order(sort_column + " " + sort_direction).search(params[:search])
      else
        @parts = Part.order(sort_column + " " + sort_direction).where(category: filter_category).search(params[:search])
      end}
      format.xls {if filter_category.blank?
        @parts = Part.order(sort_column + " " + sort_direction).search(params[:search])
      else
        @parts = Part.order(sort_column + " " + sort_direction).where(category: filter_category).search(params[:search])
      end}
      format.json { render json: @parts }
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @part = Part.find(params[:id])

    if params[:download]
      send_data(render_to_string, :filename => "#{@part.partnumber}-label.html", :type => "text/html")
    else

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @part }
      end
    end
  end

  # GET /parts/new
  # GET /parts/new.json
  def new
    @part = Part.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @part }
    end
  end

  # GET /parts/1/edit
  def edit
    @part = Part.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(params[:part])

    respond_to do |format|
      if @part.save
        format.html { redirect_to new_part_path, notice: 'Part was successfully created.' }
        format.json { render json: @part, status: :created, location: @part }
      else
        format.html { render action: "new" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parts/1
  # PUT /parts/1.json
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    respond_to do |format|
      format.html { redirect_to parts_url }
      format.json { head :no_content }
    end
  end
  
  def invreset
    Part.update_all(:invcount => 0)
    Part.update_all(:invuser => nil)
    Part.update_all(:invscandate => nil)
    redirect_to parts_url, notice: 'All inventory counts reset to zero.'
  end
  
  def sort_column
    Part.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
  def filter_category
    Part.uniq.pluck(:category).include?(params[:typefilter]) ? params[:typefilter] : nil
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= simple_form_for(@part) do |f| %>

  <div class="form-inputs">
    <%= f.input :partnumber, label: "Part Number" %>
    <%= f.input :name %>
    <%= f.input :description, :input_html => {:style => 'width: 365px; height: 100px'} %>
    <%= f.input :category %>
    <%= f.input :location %>
    <%= f.input :cost %>
    <%= f.input :onhand, label: "On Hand" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<tr onclick="window.location.href = '<%= part_path(part) %>'" style="cursor: pointer">
  <td><%= part.name %></td>
  <td><%= part.category %></td>
  <td><%= part.location %></td>
  <% if current_user.invmode == TRUE %>
   	<td style="text-align: center" title="<%= if part.invuser? then ("Counted by: " + part.invuser + " on " + part.invscandate.to_s) else "Uncounted" end %>"><%= part.invcount %></td>
  <% else %>
  	<td style="text-align: right"><%= number_to_currency(part.cost, :unit => "$") %></td>
  <% end %>
  <td style="text-align: center"><%= part.onhand %></td>
  <td><%= link_to (content_tag :i, "", class: "icon-list-alt"), part_path(part), :class => "btn" %></td>
  <td><%= link_to (content_tag :i, "", class: "icon-edit"), edit_part_path(part), :class => "btn" %></td>
</tr>

app/views/parts/edit.html.erb
<% if current_user.invmode == TRUE %>
	<h3>Inventorying <%= @part.name %></h3>
	<p>***Adjust "On Hand" quantity to match number of parts counted.</p><br />
	<% if !params[:scan] %>
	<% else %>
		<% if @part.invcount? %>
			<% @part.invcount = (@part.invcount + (params[:scan]).to_i) %>
			<% @part.invuser = current_user.name + (if (params[:scan]).to_i > 1 then " (Manual Entry)" else "" end) %>
			<% @part.invscandate = Time.now %>
			<% @part.save %>
		<% else %>
			<% @part.invcount = (0 + (params[:scan]).to_i) %>
			<% @part.invuser = current_user.name + (if (params[:scan]).to_i > 1 then " (Manual Entry)" else "" end) %>
			<% @part.invscandate = Time.now %>
			<% @part.save %>
		<% end %>
	<% end %>
<% else %>
	<h3>Editing <%= @part.name %></h3>
<% end %>

<%= render 'form' %>

<%= link_to (content_tag :i, "", class: "icon-list-alt"), @part, :class => "btn" %> |
<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back %>

app/views/parts/index.csv.erb
<% if user_signed_in? %>
	<% if current_user.invmode == TRUE %>
		Part Name,Part #,Description,Category,Location,Cost,Qty On Hand,Inv Count,Scanned By,Scan Date
		<% @parts.each do |part| %>
		"<%= part.name %>","<%= part.partnumber %>","<%= part.description %>","<%= part.category %>","<%= part.location %>","<%= part.cost %>","<%= part.onhand %>","<%= part.invcount %>","<%= part.invuser %>","<%= part.invscandate.to_s %>"
		<% end %>
	<% else %>
		Part Name,Part #,Description,Category,Location,Cost,Qty On Hand
		<% @parts.each do |part| %>
		"<%= part.name %>","<%= part.partnumber %>","<%= part.description %>","<%= part.category %>","<%= part.location %>","<%= part.cost %>","<%= part.onhand %>"
		<% end %>
	<% end %>
<% end %>

app/views/parts/index.html.erb
<% if user_signed_in? %>
	  <div>
	    <%= form_tag parts_path,  :method => 'get' do %>
	      <p>
	        <%= text_field_tag :search, params[:search] %>
	        <%= select_tag :typefilter, options_for_select(Part.uniq.pluck(:category).collect{ |u| [u, u] }, :selected => params[:typefilter]), {:include_blank => true} %>
	        <%= submit_tag "Lookup", :name => nil, class: "btn btn-primary" %> <small>(Search part names/numbers and filter by category)</small>
	      </p>
	    <% end %>
	  </div>
	
	<script language="JavaScript">
		document.getElementById('search').focus();
	</script>
	
	<h2>Part Listing</h2>
	<p><%= link_to 'Add Part', new_part_path %>
		<% if current_user.invmode == TRUE %>
			| <%= link_to "Reset Inventory Counts", invreset_part_path(12), :confirm => "are you sure?" %>
		<% else %>
		<% end %>
	</p>
	<table class="table table-striped">
	  <thead>
		  <tr>
		    <th><%= sortable "name", "Part Name", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "category", "Category", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "location", "Location", params[:search], params[:typefilter] %></th>
		    <% if current_user.invmode == TRUE %>
		        <th style="text-align: center"><%= sortable "invcount", "Inv Qty", params[:search], params[:typefilter] %></th>
		    <% else %>
		    	<th style="text-align: center"><%= sortable "cost", "Cost", params[:search], params[:typefilter] %></th>
			<% end %>
		    <th style="text-align: center"><%= sortable "onhand", "On Hand", params[:search], params[:typefilter] %></th>
		    <th></th>
		    <th></th>
		  </tr>
	  </thead>
	  <tbody>
		<%= render @parts %>
	  </tbody>
	</table>
	<%= will_paginate @parts %>
	<br />
<p>
  Download:
  <% if !params[:search] %>
    <%= link_to "CSV", parts_path + ".csv" %> |
    <%= link_to "Excel", parts_path + ".xls" %>
  <% else %>
    <%= link_to "CSV", parts_path + ".csv?search=" + params[:search] + "&typefilter=" + params[:typefilter] %> |
    <%= link_to "Excel", parts_path + ".xls?search=" + params[:search] + "&typefilter=" + params[:typefilter] %>
  <% end %>
</p>
<% end %>

app/views/parts/index.xls.erb
<% if user_signed_in? %>
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
	  <% if current_user.invmode == TRUE %>
	  <Row>
        <Cell><Data ss:Type="String">Part Name</Data></Cell>
        <Cell><Data ss:Type="String">Part #</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
        <Cell><Data ss:Type="String">Location</Data></Cell>
        <Cell><Data ss:Type="String">Cost</Data></Cell>
        <Cell><Data ss:Type="String">On Hand</Data></Cell>
        <Cell><Data ss:Type="String">Inv Count</Data></Cell>
        <Cell><Data ss:Type="String">Scanned By</Data></Cell>
        <Cell><Data ss:Type="String">Date Scanned</Data></Cell>
      </Row>
      <% @parts.each do |part| %>
      <Row>
        <Cell><Data ss:Type="String"><%= part.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.partnumber %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.category %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.location %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.cost %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.onhand %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.invcount %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.invuser %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.invscandate.to_s %></Data></Cell>
      </Row>
      <% end %>
	  <% else %>
      <Row>
        <Cell><Data ss:Type="String">Part Name</Data></Cell>
        <Cell><Data ss:Type="String">Part #</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
        <Cell><Data ss:Type="String">Location</Data></Cell>
        <Cell><Data ss:Type="String">Cost</Data></Cell>
        <Cell><Data ss:Type="String">On Hand</Data></Cell>
      </Row>
      <% @parts.each do |part| %>
      <Row>
        <Cell><Data ss:Type="String"><%= part.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.partnumber %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.category %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.location %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.cost %></Data></Cell>
        <Cell><Data ss:Type="String"><%= part.onhand %></Data></Cell>
      </Row>
      <% end %>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>
<% end %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>

app/views/parts/show.html.erb
<% if params[:download] %>
<script type="text/javascript">
	function findPrinter() {
		var applet = document.jzebra;
		if (applet != null) {
			applet.findPrinter("zebra");
		}
		monitorFinding();
	}

	function print() {
		var applet = document.jzebra;
		if (applet != null) {
			applet.append("^XA\n");
			applet.append("^FO215,15^BQ,2,4^FDQA,<%= edit_part_url(@part) + "?scan=1" %>^FS\n");
			applet.append("^FO430,15^ADN,20,12^FD<%= @part.name[0..14] %>^FS\n");
			applet.append("^FO430,35^ADN,20,12^FD<%= @part.name[15..29] %>^FS\n");
			applet.append("^FO430,65^ADN,20,12^FD<%= @part.description[0..14] %>^FS\n");
			applet.append("^FO430,85^ADN,20,12^FD<%= @part.description[15..29] %>^FS\n");
			applet.append("^FO430,105^ADN,20,12^FD<%= @part.description[30..44] %>^FS\n");
			applet.append("^FO430,150^ADN,20,12^FDP/N: <%= @part.partnumber %>^FS\n");
			applet.append("^FO430,175^ADN,20,12^FDID: <%= @part.id %>^FS\n");
			applet.append("^XZ\n"); 
			applet.print();
		}
		monitorPrinting();
    }

    function chr(i) {
		return String.fromCharCode(i);
	}

	function monitorPrinting() {
		var applet = document.jzebra;
		if (applet != null) {
			if (!applet.isDonePrinting()) {
				window.setTimeout('monitorPrinting()', 100);
			} else {
				var e = applet.getException();
				alert(e == null ? "Printed Successfully" : "Exception occured: " + e.getLocalizedMessage());
			}
		} else {
	    	alert("Applet not loaded!");
		}
	}

	function monitorFinding() {
		var applet = document.jzebra;
		if (applet != null) {
			if (!applet.isDoneFinding()) {
				window.setTimeout('monitorFinding()', 100);
			} else {
				var printer = applet.getPrinter();
				alert(printer == null ? "Printer not found" : "Printer \"" + printer + "\" found");
			}
		} else {
			alert("Applet not loaded!");
		}
	}

   </script>

	<p <%= params[:download] ? ("style='display: inline'").html_safe : ("style='display: none'").html_safe %>>
		<applet name="jzebra" code="jzebra.PrintApplet.class" archive="./jzebra.jar" width="50px" height="50px">
	      <param name="printer" value="zebra">
	    </applet>
		<input type=button onClick="print()" value="Print" class="btn btn-primary"/>
		<h3>Click print button above to print label</h3>
	</p>   
<% else %>

<div class="row">
	<div class="span9 offset1">
		<div class="well">
			<h4><%= @part.name %> Detail <p class="pull-right">Inventory Label: <%= link_to (content_tag :i, "", class: "icon-qrcode"), part_path(@part, :download => true), :class => "btn", :title => "Download inventory label print file" %></p></h4>
			<br />
			<p>
			  <b>Part #:</b>
			  <%= @part.partnumber %>
			</p>
			
			<p>
			  <b>Description:</b>
			  <%= @part.description %>
			</p>
			
			<p>
			  <b>Category:</b>
			  <%= @part.category %>
			</p>
			
			<p>
			  <b>Location:</b>
			  <%= @part.location %>
			</p>
			
			<p>
			  <b>Cost:</b>
			  <%= number_to_currency(@part.cost, :unit => "$") %>
			</p>
			
			<p>
			  <b>Qty On Hand:</b>
			  <%= @part.onhand %>
			</p>
			
			<br />

			<%= link_to (content_tag :i, "", class: "icon-edit"), edit_part_path(@part), :class => "btn" %>
			<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>
			<%= link_to (content_tag :i, "", class: "icon-trash"), @part, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn pull-right" %>
		</div>
	</div>
</div>
<% end %>