config/routes.rb
EquipmentTracker::Application.routes.draw do

  resources :equipment do
    collection do
      post :import
    end
    resources :loans
    resources :services do
      resources :serviceparts
      resources :serviceimages
    end
    member do
      match 'startoggle' => 'equipment#startoggle'
      match 'invreset' => 'equipment#invreset'
    end
  end
  
  resources :services do
    member do
      match 'serviceRequest' => 'services#serviceRequest'
    end
    resources :serviceparts
    resources :serviceimages
  end
  
  resources :serviceparts do
    resources :parts
  end
  
  resources :serviceimages
  
  resources :parts do
    member do
      match 'invreset' => 'parts#invreset'
    end
  end

  resources :loans
  
  devise_for :users
  
  resources :users do
    member do
      match 'invmodetoggle' => 'users#invmodetoggle'
    end
  end

  get 'about' => 'pages#about'
  
  get 'part' => 'part#index'
  
  get 'archived' => 'equipment#archived'
  
  get 'service' => 'services#index'

  get 'holdlist' => 'equipment#holdlist'    

  get 'openloan' => 'loans#index' 

  get 'equipment' => 'equipment#index'
  
  root :to => 'equipment#index'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :barcode, :crew, :description, :dop, :equipmenttype, :fueltype, :manufacturer, :performance, :responsible, :serialnumber, :storagelocation, :supplier, :unitname, :image, :hold, :holddate, :archived, :inservicedate, :counter, :invcount, :invuser, :invscandate, :gpsurl
  
  has_attached_file :image, styles: { thumb: "150x150>"}
  has_paper_trail
  
  validates :barcode, presence: true
  validates :user_id, presence: true
  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
                               size: { less_than: 5.megabytes }
  
  belongs_to :user
  has_many :services, dependent: :destroy
  has_many :loans, dependent: :destroy
  
  scope :active, where('archived IS NULL or archived=(?)', false)
  scope :inactive, where('archived=(?)', true)
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(barcode) LIKE lower(?) OR lower(description) LIKE lower(?) OR lower(unitname) LIKE lower(?)', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
  
  def servicecostTotal
    services.map do |i|
      if !i.servicecost.blank?
        then i.servicecost
      else servicecostTotal=0.00
      end
    end.sum
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Equipment.create! row.to_hash
    end
  end
  
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_filter :authenticate_user! #, except: [:index]
  # GET /equipment
  # GET /equipment.json
  helper_method :sort_column, :sort_direction, :filter_equipmenttype
  
  def index
    if filter_equipmenttype.blank?
      @equipment = Equipment.active.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).search(params[:search])
    else
      @equipment = Equipment.active.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).where(equipmenttype: filter_equipmenttype).search(params[:search])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.csv {if filter_equipmenttype.blank?
        @equipment = Equipment.active.order(sort_column + " " + sort_direction).search(params[:search])
      else
        @equipment = Equipment.active.order(sort_column + " " + sort_direction).where(equipmenttype: filter_equipmenttype).search(params[:search])
      end}
      format.xls {if filter_equipmenttype.blank?
        @equipment = Equipment.active.order(sort_column + " " + sort_direction).search(params[:search])
      else
        @equipment = Equipment.active.order(sort_column + " " + sort_direction).where(equipmenttype: filter_equipmenttype).search(params[:search])
      end}
      format.json { render json: @equipment }
    end
  end
  
  def archived
    if filter_equipmenttype.blank?
      @equipment = Equipment.inactive.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).search(params[:search])
    else
      @equipment = Equipment.inactive.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).where(equipmenttype: filter_equipmenttype).search(params[:search])
    end
    
    respond_to do |format|
      format.html # archived.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.find(params[:id])
    if !@equipment.services.blank?
      @lastservicehours = Equipment.find(params[:id]).services.where('operatinghours IS NOT NULL').order('servicedate ASC').last
      @lastservicemiles = Equipment.find(params[:id]).services.where('mileage IS NOT NULL').order('servicedate ASC').last
    end
    if params[:download]
      send_data(render_to_string, :filename => "#{@equipment.barcode}-label.html", :type => "text/html")
    else
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @equipment }
      end
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = current_user.equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = current_user.equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        if params[:commit] == "Add/Update Equipment"
          format.html { redirect_to new_equipment_path, notice: 'Equipment was successfully created.' }
        else
          format.html { redirect_to equipment_path(@equipment), notice: 'Equipment was successfully created. Click the QR Code button to download the label file.' }
        end  
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    if @equipment.archived.blank?
      @equipment.archived = true
      @equipment.save
    else
      @equipment.destroy
    end

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
  
  def holdlist
    @equipment = Equipment.order(sort_column + " " + sort_direction).page(params[:page]).per_page(20).where(:hold => true)

    respond_to do |format|
      format.html # holdlist.html.erb
      format.json { render json: @equipment }
    end
  end
  
  def startoggle
    @equipment = Equipment.find(params[:id])
    holdnotes = "Placed on hold by " + current_user.name + " on " + Date.today.to_s
    if user_signed_in?
      if !@equipment.hold.blank?
        if @equipment.hold=false
          @equipment.hold=true
          @equipment.holdnotes=holdnotes
          @equipment.holddate=Date.today
          @equipment.save
          redirect_to Rails.cache.read("whereyouare"), notice: 'Item has been placed in hold list.'
        else
          @equipment.hold=false
          @equipment.holdnotes=""
          @equipment.holddate=nil
          @equipment.save
          redirect_to Rails.cache.read("whereyouare"), notice: 'Item has been removed from hold list.'
        end
      else
        @equipment.hold=true
        @equipment.holdnotes=holdnotes
        @equipment.holddate=Date.today
        @equipment.save
        redirect_to Rails.cache.read("whereyouare"), notice: 'Item has been placed in hold list.'
      end
    end
  end
  
  def invreset
    Equipment.update_all(:invcount => 0)
    Equipment.update_all(:invuser => nil)
    Equipment.update_all(:invscandate => nil)
    redirect_to root_url, notice: 'All inventory counts reset to zero.'
  end
  
  def import
    Equipment.import(params[:file])
    redirect_to root_url, notice: "Equipment imported."
  end
  
  private
  
  def sort_column
    Equipment.column_names.include?(params[:sort]) ? params[:sort] : "unitname"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
  def filter_equipmenttype
    Equipment.uniq.pluck(:equipmenttype).include?(params[:typefilter]) ? params[:typefilter] : nil
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/archived.html.erb
<% if user_signed_in? %>
	  <div>
	    <%= form_tag archived_path,  :method => 'get' do %>
	      <p>
	        <%= text_field_tag :search, params[:search] %>
	        <%= select_tag :typefilter, options_for_select(Equipment.uniq.pluck(:equipmenttype).collect{ |u| [u, u] }, :selected => params[:typefilter]), {:include_blank => true} %>
	        <%= submit_tag "Lookup", :barcode => nil, class: "btn btn-primary" %><br />
	        <small>(Enter Barcode, Crew or Serial number and/or select equipment type to filter)</small>
	      </p>
	    <% end %>
	  </div>	
	
	<script language="JavaScript">
		document.getElementById('search').focus();
	</script>
	
	<h2>Archived Equipment Listing</h2>
	<table class="table table-striped">
	  <thead>
		  <tr>
		    <th><%= sortable "barcode", "Barcode", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "unitname", "Unit Name", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "crew", "Crew", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "dop", "DOP", params[:search], params[:typefilter] %></th>
		    <% if current_user.invmode == TRUE %>
		        <th style="text-align: center"><%= sortable "invcount", "Inv Qty", params[:search], params[:typefilter] %></th>
		    <% else %>
			    <th style="text-align: center"><%= sortable "counter", "Scans", params[:search], params[:typefilter] %></th>
			<% end %>
		    <th>Description</th>
		  </tr>
	  </thead>
	  <tbody>
		<%= render @equipment %>
	  </tbody>
	</table>
	<%= will_paginate @equipment %>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>

app/views/equipment/index.html.erb
<% if user_signed_in? %>
	  <div>
	    <%= form_tag root_path,  :method => 'get' do %>
	      <p>
	        <%= text_field_tag :search, params[:search] %>
	        <%= select_tag :typefilter, options_for_select(Equipment.uniq.pluck(:equipmenttype).collect{ |u| [u, u] }, :selected => params[:typefilter]), {:include_blank => true} %>
	        <%= submit_tag "Lookup", :barcode => nil, class: "btn btn-primary" %><br />
	        <small>(Search and/or select equipment type to filter)</small>
	      </p>
	    <% end %>
	  </div>	
	
	<script language="JavaScript">
		document.getElementById('search').focus();
	</script>
	
	<h2>Equipment Listing</h2>
	<p><%= link_to 'Add Equipment', new_equipment_path %>
		<% if current_user.invmode == TRUE %>
			| <%= link_to "Reset Inventory Counts", invreset_equipment_path(12), :confirm => "are you sure?" %>
		<% else %>
		<% end %></p>
	<table class="table table-striped">
	  <thead>
		  <tr>
		    <th><%= sortable "barcode", "Barcode", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "unitname", "Unit Name", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "crew", "Crew", params[:search], params[:typefilter] %></th>
		    <th><%= sortable "dop", "DOP", params[:search], params[:typefilter] %></th>
		    <% if current_user.invmode == TRUE %>
		        <th style="text-align: center"><%= sortable "invcount", "Inv Qty", params[:search], params[:typefilter] %></th>
		    <% else %>
			    <th style="text-align: center"><%= sortable "counter", "Scans", params[:search], params[:typefilter] %></th>
			<% end %>
		    <th>Description</th>
		  </tr>
	  </thead>
	  <tbody>
		<%= render @equipment %>
	  </tbody>
	</table>
	<%= will_paginate @equipment %>
<p>
  Download:
  <% if !params[:search] %>
    <%= link_to "CSV", equipment_index_path + ".csv" %> |
    <%= link_to "Excel", equipment_index_path + ".xls" %>
  <% else %>
    <%= link_to "CSV", equipment_index_path + ".csv?search=" + params[:search] + "&typefilter=" + params[:typefilter] %> |
    <%= link_to "Excel", equipment_index_path + ".xls?search=" + params[:search] + "&typefilter=" + params[:typefilter] %>
  <% end %>
</p>
<% end %>

app/views/equipment/show.html.erb
<% if params[:download] %>
<script type="text/javascript">
	function findPrinter() {
		var applet = document.jzebra;
		if (applet != null) {
			applet.findPrinter("zebra");
		}
		monitorFinding();
	}

	function print() {
		var applet = document.jzebra;
		if (applet != null) {
			applet.append("^XA\n");
			applet.append("^FO215,15^BQ,2,5^FDQA,<%= equipment_url(@equipment) %>^FS\n");
			applet.append("^FO430,80^ADN,40,27^FD<%= @equipment.crew %>^FS\n");
			applet.append("^FO430,150^ADN,20,12^FDS/N: <%= @equipment.serialnumber.last(4) %>^FS\n");
			applet.append("^FO430,175^ADN,20,12^FD#<%= @equipment.id %>^FS\n");
			applet.append("^FO430,15^ADN,20,12^FD<%= @equipment.dop %>^FS\n");
			applet.append("^XZ\n"); 
			applet.print();
		}
		monitorPrinting();
    }

    function chr(i) {
		return String.fromCharCode(i);
	}

	function monitorPrinting() {
		var applet = document.jzebra;
		if (applet != null) {
			if (!applet.isDonePrinting()) {
				window.setTimeout('monitorPrinting()', 100);
			} else {
				var e = applet.getException();
				alert(e == null ? "Printed Successfully" : "Exception occured: " + e.getLocalizedMessage());
			}
		} else {
	    	alert("Applet not loaded!");
		}
	}

	function monitorFinding() {
		var applet = document.jzebra;
		if (applet != null) {
			if (!applet.isDoneFinding()) {
				window.setTimeout('monitorFinding()', 100);
			} else {
				var printer = applet.getPrinter();
				alert(printer == null ? "Printer not found" : "Printer \"" + printer + "\" found");
			}
		} else {
			alert("Applet not loaded!");
		}
	}

   </script>

	<p <%= params[:download] ? ("style='display: inline'").html_safe : ("style='display: none'").html_safe %>>
		<applet name="jzebra" code="jzebra.PrintApplet.class" archive="./jzebra.jar" width="50px" height="50px">
	      <param name="printer" value="zebra">
	    </applet>
		<input type=button onClick="print()" value="Print" class="btn btn-primary"/>
		<h3>Click print button above to print label</h3>
	</p>   
<% else %>
	<% if !params[:scan] %>
		<% if !current_user.invmode %>
			<% if @equipment.counter? %>
				<% @equipment.counter = (@equipment.counter + 1) %>
				<% @equipment.save %>
			<% else %>
				<% @equipment.counter = 1 %>
				<% @equipment.save %>
			<% end %>
		<% else %>
			<% if @equipment.invcount? %>
				<% @equipment.invcount = (@equipment.invcount + 1) %>
				<% @equipment.invuser = current_user.name %>
				<% @equipment.invscandate = Time.now %>
				<% @equipment.save %>
			<% else %>
				<% @equipment.invcount = 1 %>
				<% @equipment.invuser = current_user.name %>
				<% @equipment.invscandate = Time.now %>
				<% @equipment.save %>
			<% end %>
		<% end %>
	<% else %>
		<% if !current_user.invmode %>
			<% if @equipment.counter? %>
				<% @equipment.counter = (@equipment.counter + (params[:scan]).to_i) %>
				<% if @equipment.counter < 0 %>
					<% @equipment.counter = 0 %>
				<% end %>
				<% @equipment.save %>
			<% else %>
				<% @equipment.counter = (0 + (params[:scan]).to_i) %>
				<% if @equipment.counter < 0 %>
					<% @equipment.counter = 0 %>
				<% end %>
				<% @equipment.save %>
			<% end %>
		<% else %>
			<% if @equipment.invcount? %>
				<% @equipment.invcount = (@equipment.invcount + (params[:scan]).to_i) %>
				<% @equipment.invuser = current_user.name + " (Manual Entry)" %>
				<% @equipment.invscandate = Time.now %>
				<% @equipment.save %>
			<% else %>
				<% @equipment.invcount = (0 + (params[:scan]).to_i) %>
				<% @equipment.invuser = current_user.name + " (Manual Entry)" %>
				<% @equipment.invscandate = Time.now %>
				<% @equipment.save %>
			<% end %>
		<% end %>
	<% end %>
<div class="row">
	<div class="span9 offset1">
		<div class="well" id="EquipmentBox">
			<p class="hero-unit">
			  <% if @equipment.image? %>
			  	<%= image_tag @equipment.image(:thumb), class: "pull-right" %>
			  <% else %>
			  	<small><%= link_to 'ADD IMAGE', edit_equipment_path(@equipment), class: "pull-right" %></small>
			  <% end %>
			  <% if !@equipment.hold.blank? %>
			  	<% if @equipment.hold=false %>
		  			<%=link_to( image_tag("star-empty.png"), startoggle_equipment_path(@equipment), :onclick => Rails.cache.write("whereyouare", request.original_url), :title => "Add to hold list.") %>
			  	<% else %>
			  		<% if !@equipment.holddate.blank? %>
			  			<% if ((Date.today - @equipment.holddate)<30) %>
			  				<%=link_to( image_tag("star.png"), startoggle_equipment_path(@equipment), :onclick => Rails.cache.write("whereyouare", request.original_url), :title => if @equipment.holdnotes? then @equipment.holdnotes else "Remove from hold list." end, data: { confirm: 'Are you sure you want to remove this item from hold?' }) %>
			  			<% else %>
			  				<%=link_to( image_tag("star-red.png"), startoggle_equipment_path(@equipment), :onclick => Rails.cache.write("whereyouare", request.original_url), :title => if @equipment.holdnotes? then @equipment.holdnotes else "Remove from hold list." end, data: { confirm: 'Are you sure you want to remove this item from hold?' }) %>
			  			<% end %>
			  		<% else %>
			  			<%=link_to( image_tag("star.png"), startoggle_equipment_path(@equipment), :onclick => Rails.cache.write("whereyouare", request.original_url), :title => if @equipment.holdnotes? then @equipment.holdnotes else "Remove from hold list." end, data: { confirm: 'Are you sure you want to remove this item from hold?' }) %>
			  		<% end %>
			  	<% end %>
			  <% else %>
			  	<%=link_to( image_tag("star-empty.png"), startoggle_equipment_path(@equipment), :onclick => Rails.cache.write("whereyouare", request.original_url), :title => "Add to hold list.") %>
			  <% end %>
			  <b><%= @equipment.unitname %></b></br>
			  <small>
			  	<%= @equipment.barcode %></br>
			  	<b>DOP:</b> <%= @equipment.dop %></br>
			  	<b>ISD:</b> <%= @equipment.inservicedate %></br>
			  </small>
			</p>
			<% if @equipment.archived? %>
				<%= link_to (content_tag :i, "", class: "icon-arrow-down", :title => 'Archived'), archived_path, :class => "archive" %>
			<% end %>

		<!-- Button trigger modal -->
		<button class="btn btn-primary" data-toggle="modal" data-target="#addServiceModal">
		  Add/Request Service
		</button>
		<button class="btn btn-primary" data-toggle="modal" data-target="#loansModal">
		  Loans
		</button>
		<%= link_to (content_tag :i, "", class: "icon-qrcode"), equipment_path(@equipment, :download => true), :class => "btn pull-right", :title => "Download label print file" %>
		<%= if !@equipment.gpsurl.blank? then (link_to (content_tag :i, "", class: "icon-road"), @equipment.gpsurl, :class => "btn pull-right", :title => "Track via GPS", :target => "_blank") else "" end %>
		<br /><br />
		<!-- Service Modal -->
		<div class="modal hide fade in" id="addServiceModal" tabindex="-1" role="dialog" aria-labelledby="addServiceModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        <h4 class="modal-title" id="addServiceModalLabel"><%= @equipment.unitname %><%= if !@equipment.crew.empty? then ("-" + @equipment.crew) else "" end %></h4>
		      </div>
		      <div class="modal-body">
				<%= render 'serviceForm' %>
		      </div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
		
		<!-- Loans Modal -->
		<div class="modal hide fade in" id="loansModal" tabindex="-1" role="dialog" aria-labelledby="loansModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        <h4 class="modal-title" id="loansModalLabel"><%= @equipment.unitname %><%= if !@equipment.crew.empty? then ("-" + @equipment.crew) else "" end %></h4>
		      </div>
		      <div class="modal-body">
		        <p>
					<h4>Loan History:<button type="button" class="btn btn-info pull-right" data-dismiss="modal">Cancel</button><button class="btn btn-primary pull-right" data-dismiss="modal" data-toggle="modal" data-target="#addLoanModal">Add Loan</button></h4>
					<% if @equipment.loans.blank? %>
						<p>No loans saved for this item.</p>
					<% else %>
						<table class="table table-striped">
		                  <thead>
		                      <tr>
		                          <th>Loaned To</th>
		                          <th>Loaned On</th>
		                          <th>Loaned By</th>
		                          <th>Returned On</th>
		                          <th></th>
		                      </tr>
		                  </thead>
		                  <tbody>
		                        <%= render @equipment.loans.order("loandate DESC") %>
		                  </tbody>
		                </table>
	                <% end %>
				</p>
		      </div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
		
		<!-- Loans Modal -->
		<div class="modal hide fade in" id="addLoanModal" tabindex="-1" role="dialog" aria-labelledby="addLoanModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" data-toggle="modal" data-target="#loansModal">&times;</button>
		        <h4 class="modal-title" id="addLoanModalLabel">Add loan on <%= @equipment.unitname %><%= if !@equipment.crew.empty? then ("-" + @equipment.crew) else "" end %></h4>
		      </div>
		      <div class="modal-body">
		        <p>
					<%= simple_form_for([@equipment, @equipment.loans.build], html: { class: "form-horizontal"}) do |f| %>
					  <%= f.input :loanedto, label: "Loaned To", :input_html => {:autofocus => ''} %>
					  <%= f.input :loandate, label: "Loaned On", :input_html => {:style => 'width: 105px'} %>
					  <%= f.input :loanedby, label: "Loaned By", :input_html => { :value => current_user.name} %>
	
					<div class="form-actions">
						<%= f.button :submit, class: "btn btn-primary" %>
						<button type="button" class="btn btn-info" data-dismiss="modal" data-toggle="modal" data-target="#loansModal">Cancel</button>
					</div>
					<% end %>
				</p>
			</div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->	
			
			<p>
			  <b>Description:</b>
			  <%= @equipment.description %>
			</p>
			
			<p>
			  <b>Manufacturer:</b>
			  <%= @equipment.manufacturer %>
			</p>
			
			<p>
			  <b>Equipment Type:</b>
			  <%= @equipment.equipmenttype %>
			</p>
			
			<p>
			  <b>Serial Number/VIN:</b>
			  <%= @equipment.serialnumber %>
			</p>
			
			<p>
			  <b>Fuel Type:</b>
			  <%= @equipment.fueltype %>
			</p>
			
			<p>
			  <b>Performance (1=New, 2=Used, 3=Old):</b>
			  <%= @equipment.performance %>
			</p>
			
			<p>
			  <b>Storage Location:</b>
			  <%= @equipment.storagelocation %>
			</p>
			
			<p>
			  <b>Crew:</b>
			  <%= @equipment.crew %>
			</p>
			
			<p>
			  <b>Responsible Person:</b>
			  <%= @equipment.responsible %>
			</p>
			
			<p>
			  <b>Supplier:</b>
			  <%= @equipment.supplier %>
			</p>
			
			<p>
			  <b>Total Service Cost:</b>
			  <%= number_to_currency(@equipment.servicecostTotal, :unit => "$") %>
			</p>
			
			<p>
				<% if !@equipment.services.blank? %>
					<b>Latest 
						<% if @equipment.equipmenttype == "Vehicle" %>
					    	Mileage:
					    <% else %>
					    	Operating Hours:
					    <% end %>
					</b>
					<% if @equipment.equipmenttype == "Vehicle" %>
						<% if !@lastservicemiles.blank? %>
					    	<%= @lastservicemiles.mileage %> on <%= @lastservicemiles.servicedate %>
					    <% end %>	
				    <% else %>
				    	<% if !@lastservicehours.blank? %>
					    	<%= @lastservicehours.operatinghours %> on <%= @lastservicehours.servicedate %>
						<% end %>
				    <% end %>
				<% else %>
					<p>No Service History</p>
				<% end %>
			</p>
			<p>
				<b>Scan count: </b> 
				<% if @equipment.counter? %>
					<%= @equipment.counter %>
				<% else %>
					0
				<% end %>
			</p>
			
			<br />
			<%= link_to (content_tag :i, "", class: "icon-arrow-left"), :back, :class => "btn" %>
			<%= link_to (content_tag :i, "", class: "icon-edit"), edit_equipment_path(@equipment), :class => "btn" %>
			<%= link_to (content_tag :i, "", class: "icon-trash"), @equipment, method: :delete, data: { confirm: 'Are you sure you want to delete this equipment (It will be archived if it is active)? !! IF IT IS ARCHIVED ALREADY IT WILL BE PERMANENTLY DELETED !!' }, :class => "btn pull-right" %>
		</div>
		<div class="well" %>
			<h4>Service History</h4>
			<% if !@equipment.services.blank? %>
				<table class="table table-striped">
					<thead>
						<tr>
							<th title="Incomplete"><span class="icon-flag"></span></th>
						    <th>Service Performed</th>
						    <th>Unit</th>
						    <th>Service Date</th>
						    <% if @equipment.equipmenttype == "Vehicle" %>
						    	<th>Mileage</th>
						    <% else %>
						    	<th>Operating Hours</th>
						    <% end %>
						    <th style="text-align: center">Cost</th>
						    <th></th>
						    <th></th>
						</tr>
					</thead>
					<tbody>
						<%= render @equipment.services.order("servicedate desc") %>
					</tbody>
				</table>
			<% else %>
			<p>There is no service history for this unit.</p>
			<% end %>
		</div>
	</div>
</div>
<% end %>