config/routes.rb
EquipmentTracker::Application.routes.draw do

  resources :equipment do
    collection do
      post :import
    end
    resources :loans
    resources :services do
      resources :serviceparts
      resources :serviceimages
    end
    member do
      match 'startoggle' => 'equipment#startoggle'
      match 'invreset' => 'equipment#invreset'
    end
  end
  
  resources :services do
    member do
      match 'serviceRequest' => 'services#serviceRequest'
    end
    resources :serviceparts
    resources :serviceimages
  end
  
  resources :serviceparts do
    resources :parts
  end
  
  resources :serviceimages
  
  resources :parts do
    member do
      match 'invreset' => 'parts#invreset'
    end
  end

  resources :loans
  
  devise_for :users
  
  resources :users do
    member do
      match 'invmodetoggle' => 'users#invmodetoggle'
    end
  end

  get 'about' => 'pages#about'
  
  get 'part' => 'part#index'
  
  get 'archived' => 'equipment#archived'
  
  get 'service' => 'services#index'

  get 'holdlist' => 'equipment#holdlist'    

  get 'openloan' => 'loans#index' 

  get 'equipment' => 'equipment#index'
  
  root :to => 'equipment#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		&copy;<%= Time.now.year %> <%= link_to "Heritage Landscape Services", "http://hls2.com" %>
		by <%= link_to "Ian Randolph", "http://ianrandolph.com" %>
	</small> |
	<small>
		<%= link_to "Report Issues", "https://bitbucket.org/CtrlR/equipmenttracker/issues" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<% if !params[:download] %>
<div class="navbar navbar-fixed-top">	
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <%= link_to "Equipment Tracker", root_path, class: "brand" %>

            <div class="nav-collapse">
                <ul class="nav">
                    <li>
                        <%= link_to 'Hold List',  holdlist_path %>
                    </li>
                    <li>
                        <%= link_to 'Open Loans',  openloan_path %>
                    </li>
                    <li>
                        <%= link_to 'Service',  services_path %>
                    </li>
                    <li>
                        <%= link_to 'Parts',  parts_path %>
                    </li>
                </ul>
                <ul class="nav pull-right">
                	<% if user_signed_in? %>
                		<% if current_user.invmode == TRUE %>
						    <li style="color: red; text-align: center; font-weight: bolder; font-size: 16px; vertical-align: bottom">
						        INVENTORY MODE ON 
						    </li>
						<% end %>
	            		<li><%= link_to 'Add Equipment +',  new_equipment_path %></li>
	            		<li class="dropdown">
			              <%= link_to (current_user.name + content_tag(:b, "", class: "caret")).html_safe, "#", {class: "dropdown-toggle", :id => "drop1", :"data-toggle" => "dropdown" } %>
			              <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
			              	<li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to (if current_user.invmode == TRUE then "Inventory Mode is ON" else "Inventory Mode is OFF" end), invmodetoggle_user_path(current_user) %></a></li>
			              	<li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Reset Inventory Counts", invreset_equipment_path(12), :confirm => "are you sure?" %></a></li>
			              	<li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to 'Archived Equipment',  archived_path %></a></li>
			              	<li role="presentation" class="divider"></li>
			                <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Edit Account", edit_user_registration_path %></a></li>
			                <li role="presentation" class="divider"></li>
			                <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to 'About',  about_path %></a></li>
			                <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to "Logout", destroy_user_session_path, method: :delete %></a></li>
			              </ul>
			            </li>
                    <% else %>
                    	<li><%= link_to 'Login',  new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Equipment Tracker</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |name, msg|%>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render "layouts/footer" %>
		</div>
	</body>
</html>